### PR TITLE
BREAKING CHANGE: US135602: [AQD] Lit 2 migration - Phase 2

### PR DESCRIPTION
**Pull request by Vitalii-Misechko**
[US135602](https://rally1.rallydev.com/#/?detail=/userstory/623256595111&fdp=true): [AQD] Lit 2 migration - Phase 2

This PR makes the breaking changes required to update to Lit 2 (`lit-html` 2 and `lit-element` 3). The Lit 2 upgrade will be a coordinated effort, so **this PR should not merge at this time**.

Breaking change checklist: 

- [x] Update `lit-html` -> `^2`, `lit-element` -> `^3`, `open-wc/testing` -> `^3` (if used)
- [x] `createRenderRoot` usages -> move from LitElement to ReactiveElement 
- [x] Remove Dependabot Lit rules in `.github/dependabot.yml`
- [x] Bump any dependencies to their Lit 2 versions
- [x] Remove any manual lifecycle calls to Lit 1 reactive controllers (Eg. `this._subscriptionController.hostConnected()`, etc)
- [x] backwards-compatible changes merged

Renamed API's:
- [x] `UpdatingElement` -> `ReactiveElement`
- [x] `@internalProperty` -> `@state` (we don't use TypeScript decorators)
- [x] `static getStyles()` -> `static finalizeStyles(styles)`
- [x] `_getUpdateComplete()` -> `getUpdateComplete()`
- [x] `NodePart` -> `ChildPart`

Testing checklist: 
- [x] CI/ unit tests pass
- [x] Local testing on demo pages
- [x] Testing component in the LMS
   - [x] All dependencies point to Lit 2 version
   - [x] The dashboard loads without errors
   - [x] Settings are saved if changed
     - [x] !Some validation behavior has been changed
   - [x] Toast appears if any filter is changed
   - [x] Filtering works
   - [x] OrgUnits filter works 
   - [x] Quiz Details search works
   - [x] Export CSV and Learn More work
   - [x] Quiz Item Analysis page
     - [x] The page loads without errors in console
     - [x] Filtering works
     - [x] Question preview works
        - [x] Threre is an error `404 htmleditor/lang/en-us.js` . Ignored
        
For more information on the Lit 2 upgrade, visit https://lit.dev/docs/releases/upgrade/ or contact team Gaudi.

### Affected settings

I believe we should address that issue in a separate PR

Affected settings with d2l-input-number input:
* Quiz Details Metrics
  * Reliability coefficient
  * Quiz reliability
* Quiz Items Metrics
  * Correlation
  * Standard Deviation

### Example
delete-numeric-value-change

### CODE REVIEW

**Comment by annabelsegalld2l** [comment]
Lit 2 adds comment nodes to some elements. You can fix the tests by just ignoring them. Example: https://github.com/Brightspace/d2l-activity-alignments/pull/288/files#diff-df432fd800e68af9a6a1ee44042ae4d8ef7177d827fd0820f187681ad031c58bR32

**Comment by Vitalii-Misechko** [comment]
@annabelsegalld2l thank you for your hints! They ease my efforts for fixing.

**Comment by NicholasHallman** [comment]
Hmmm somehow the input behaviour feels worse to me but maybe that's a discussion for another story? I could see users deleting inputs, forgetting to reset them, then those inputs default to 0 instead of throwing an error to let the user know they need to fill it out.

**Review by NicholasHallman — APPROVED** [review]

**Comment by Vitalii-Misechko** [comment]
@annabelsegalld2l, could you approve this PR as well?

**Review by annabelsegalld2l — APPROVED** [review]
I do have a fix for the input-number issue under review now. I've tested the dashboard and it fixes the issues you were seeing. So you can remove those test changes related to that bug before merging, as that bug fix will be merged before the migration 😄

**Pull request merged**
