### PR TITLE
US129449 [AQ] Add Quiz Reliability Chart Card to Settings Page

### PR DESCRIPTION
**Pull request by Vitalii-Misechko**
[US129449](https://rally1.rallydev.com/#/?detail=/userstory/602529802561&fdp=true): [AQ] Add Quiz Reliability Chart Card to Settings Page

* Functional Testing 
  * [x] Browsers (Chrome, FF, Edge)
  * [x] Accessibility
  * [x] RTL
  * [x] Responsive
  * [x] Unit tests
* Security, devops, perf: N/A
* UX and docs
  * [ ] Update SVG 
  * [ ] Demo to Kevin
  
FYI @Brightspace/draco-vis

### Screenshot

image

### CODE REVIEW

**Comment by Vitalii-Misechko** [comment]
PR contains a lot of changes from master. They'll disappear as soon as @bemailloux merges master to his `US129283/average-quiz-score-settings` branch because my branch targets `US129283/average-quiz-score-settings`.

**Comment by bemailloux** [comment]
I think I might have messed something up with Git by force pushing to my branch. Sorry about that :(

**Comment by Vitalii-Misechko** [comment]
> I think I might have messed something up with Git by force pushing to my branch. Sorry about that :(

No problem

> If you rebase on top of master that might fix things

Yes, this should work

**Comment by Vitalii-Misechko** [comment]
Closed in favor of https://github.com/Brightspace/insights-assessment-quality-dashboard/pull/160

**Pull request closed without merging**
