### PR TITLE
US129441: [AQD] Align Learn More button to the right edge of the page

### PR DESCRIPTION
**Pull request by opets**
* Changes:
  *  css changes
* Functional Testing
  *  Browsers (Chrome, FF, Edge)
  *  Accessibility
  *  RTL
  *  Responsive
  *  Test cases
* Security, devops, perf: N/A

### CODE REVIEW

**Review by johngwilkinson — APPROVED** [review]

**Comment by bemailloux** [comment]
Can you include some screenshots for this in your quality notes please (at different screen sizes)?

**Comment by opets** [comment]
> Can you include some screenshots for this in your quality notes please (at different screen sizes)?

hm, this change had more sense before, without 'settings' button,
Dashboard:
image
Quiz Item Analysis:
image

**Comment by bemailloux** [comment]
> hm, this change had more sense before, without 'settings' button,

Is there a way to make the spacing consistent between "settings" and "learn more"?

**Comment by opets** [comment]
> make the spacing consistent between "settings" and "learn more"?

sure, done,
image

**Comment by opets** [comment]
FYI @Brightspace/draco-vis

**Comment by bemailloux** [comment]
>sure, done,

perfect, thanks

**Review by bemailloux — APPROVED** [review]

**Pull request merged**
