### PR TITLE
fix owner

### PR DESCRIPTION
**Pull request by dlockhart**
These need to be `Brightspace/team-name`.

### CODE REVIEW

**Review by johngwilkinson — APPROVED** [review]

**Comment by johngwilkinson** [comment]
These failing visual diffs are interesting: in a different repo I'm having something similar today, where I don't think there should be a change, but it's like things are aligned just slightly differently.

**Comment by dlockhart** [comment]
Yeah so those are from a very small pixel change to the height of subtle buttons [from this PR](https://github.com/BrightspaceUI/core/pull/2258). @svanherk you may want to post in `#web-platform` with a warning about this?

**Comment by johngwilkinson** [comment]
> Yeah so those are from a very small pixel change to the height of subtle buttons [from this PR](https://github.com/BrightspaceUI/core/pull/2258). @svanherk you may want to post in `#web-platform` with a warning about this?

Ah, thank you!

**Comment by svanherk** [comment]
>  @svanherk you may want to post in #web-platform with a warning about this?

Good call, will do!

**Pull request merged**
